version: "3.9"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      - chatdb
      - keycloak

  chatdb:
    container_name: chatdb
    image: postgres:latest
    environment:
      POSTGRES_DB: "chatdb"
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ${DB_DATA_PATH:-./pgdata/chat}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloakdb:
    container_name: keycloakdb
    image: postgres:latest
    environment:
      POSTGRES_DB: "keycloakdb"
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    command: -p 5000
    volumes:
      - ${DB_KEYCLOAK_DATA_PATH:-./pgdata/keycloak}:/var/lib/postgresql/data
    ports:
      - "5000:5000"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloakdb:5000/keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ./keycloak/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
    ports:
      - "8080:8080"
    depends_on:
      - keycloakdb
